## Assignment 2 - Data manipulation and selection

In this problem you will clean the data from our data file by removing no-data values, convert temperature values in Fahrenheit to Celsius, and split the data into separate datasets using the weather station identification code. We will start this problem by cleaning and converting our temperature data. Please perform the tasks below by writing your code into the codeblocks in each section.


### Assesment

**Assesment will be based on following criteria:**

- Creating a new dataframe called `selected` that contains select columns from the data file
- Cleaning the new dataframe by removing no-data values
- Creating a new column for temperatures converted from Fahrenheit to Celsius
- Dividing the data into separate dataframes for the Station1 and Station2
- Saving the new dataframes to CSV files
- Including comments that explain what most lines in the code do
- Answering a couple questions at the end of the problem

### Part 1

The first step for this problem is to read the data file `6153237444115dat.csv` again into a variable `data` using pandas. Remember to specify the no-data values (you can copy your code from assignment 1).

In [45]:
import pandas as pd
import numpy as np

data = None

# YOUR CODE HERE
data = pd.read_csv('data.csv')

Check that the first rows of the DataFrame look ok:

In [46]:
#CHECK THE FIRST ROW OF THE DATASET
print(data.head(1))

    USAF   WBAN  YR--MODAHRMN  DIR SPD GUS  CLG  SKC  L  M  ...     SLP  \
0  28450  99999  201705010000  174  10  14  ***  ***  *  *  ...  1009.2

     ALT    STP  MAX  MIN  PCP01  PCP06  PCP24  PCPXX  SD
0  *****  984.1  ***  ***  *****  *****  *****  *****  35

[1 rows x 33 columns]

Check the number of rows in the DataFrame:

In [47]:
row_counts = data.shape[0]
print(f'The dataset contains {row_counts} rows.')

The dataset contains 11694 rows.

### Part 2

Next, your task is to subset the data and remove rows with missing temperature values.

- Select the columns `USAF`, `YR--MODAHRMN`, `TEMP`, `MAX`, and `MIN` from the `data` dataframe and assign them to the variable `selected`
- Remove all rows from `selected` that have NoData in the column `TEMP` using the `dropna()` function

In [48]:
selected = None
selected = data[['USAF', 'YR--MODAHRMN', 'TEMP', 'MAX', 'MIN']].copy()
#remove all rows with missing values in the selected dataset

# YOUR CODE HERE
selected = selected.dropna()

Check that you selected the correct column names:

In [49]:
selected.head()

    USAF  YR--MODAHRMN TEMP  MAX  MIN
0  28450  201705010000   31  ***  ***
1  28450  201705010020   30  ***  ***
2  28450  201705010050   30  ***  ***
3  28450  201705010100   31  ***  ***
4  28450  201705010120   30  ***  ***

Check how many rows you have after removing the no-data values:

In [50]:
len(selected)

11694

### Part 3

Next, you can convert the temperature values in Fahrenheit to Celsius.

- Create a new column in `selected` called `Celsius`
- Convert the Fahrenheit temperatures from `TEMP` using the conversion formula below and store the results in the new `Celsius` column.

$$
\Large
\begin{equation}
  T_{\mathrm{Celsius}} = (T_{\mathrm{Fahrenheit}} - 32)~/~1.8
\end{equation}
$$

- Round the values in the `Celsius` column to have 0 decimals (**do not** create a new column, update the current one)
- Convert the `Celsius` values into integers (**do not** create a new column, update the current one)

In [51]:
# clean TEMP:  convert to numeric
selected['TEMP'] = pd.to_numeric(selected['TEMP'], errors='coerce')

# add new column celsius to selected dataframe by converting TEMP from Fahrenheit to Celsius
selected['Celsius'] = (selected['TEMP'] - 32) / 1.8
selected.head()

    USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0  28450  201705010000  31.0  ***  *** -0.555556
1  28450  201705010020  30.0  ***  *** -1.111111
2  28450  201705010050  30.0  ***  *** -1.111111
3  28450  201705010100  31.0  ***  *** -0.555556
4  28450  201705010120  30.0  ***  *** -1.111111

In [52]:
# Check your dataframe
selected.head()

    USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0  28450  201705010000  31.0  ***  *** -0.555556
1  28450  201705010020  30.0  ***  *** -1.111111
2  28450  201705010050  30.0  ***  *** -1.111111
3  28450  201705010100  31.0  ***  *** -0.555556
4  28450  201705010120  30.0  ***  *** -1.111111

In [53]:
# Check data types
print(selected.dtypes)

USAF              int64
YR--MODAHRMN      int64
TEMP            float64
MAX              object
MIN              object
Celsius         float64
dtype: object

### Part 4

Your next task is to divide `selected` into two separate dataframes. Please use the given variable names and write your answer to the codeblock below.

- Select all rows from the `selected` DataFrame with the `USAF` code `29980` into a variable called `Station1`
- Select all rows from the `selected` DataFrame with the `USAF` code `28450` into a variable called `Station2`

In [54]:
Station1 = None
Station2 = None

# YOUR CODE HERE
Station1 = selected[selected['USAF'] == 29980]
Station2 = selected[selected['USAF'] == 28450]

In [55]:
# Check the dataframe
print(f"Station1: \n{Station1.head()}\n")

Station1:
       USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
8770  29980  201705010000  37.0  ***  ***  2.777778
8771  29980  201705010100  37.0  ***  ***  2.777778
8772  29980  201705010200  37.0  ***  ***  2.777778
8773  29980  201705010300  37.0  ***  ***  2.777778
8774  29980  201705010400  39.0  ***  ***  3.888889

In [56]:
# Check the dataframe
print(f"Station2: \n{Station2.head()}\n")

Station2:
    USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0  28450  201705010000  31.0  ***  *** -0.555556
1  28450  201705010020  30.0  ***  *** -1.111111
2  28450  201705010050  30.0  ***  *** -1.111111
3  28450  201705010100  31.0  ***  *** -0.555556
4  28450  201705010120  30.0  ***  *** -1.111111

### Part 5

Now you can save your selections to csv files.

- Save the `Station1` DataFrame into the file `Station1.csv` (CSV format)
    - Separate the columns with commas (`,`)
    - Use only 2 decimals for the floating point numbers
- Save the `Station2` DataFrame into the file `Station2.csv` (CSV format)
    - Separate the columns with commas (`,`)
    - Use only 2 decimals for the floating point numbers

In [57]:
# we will save station data to csv files for later use and seprate columns with commas
Station1.to_csv('Station1.csv', index=False)
Station2.to_csv('Station2.csv', index=False)

### Assignment  2 summary

- Was anything unclear to you in Assignment 2?
- Did you encounter any problems?


Please write your answers and comments below.

Sources for the exercise : https://geo-python-site.readthedocs.io/en/latest/ running on a Attribution-ShareAlike 4.0 International Licence https://creativecommons.org/licenses/by-sa/4.0/deed.en

In [58]:
. yes it was easy then the 5.1 i think maybe it was me who face the problem in 5.1
. no problem at all

SyntaxError: invalid syntax (3743485619.py, line 1)